### STAGE 1: Build ###
FROM node:10.24.1-alpine AS build
WORKDIR /usr/src/watchout-client                              
COPY package.json ./
RUN npm install -g @angular/cli@9
RUN npm install
COPY . .
RUN ng build --configuration staging

### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/watchout-client/dist/WatchOut /usr/share/nginx/html
EXPOSE 80
